spring:
  application:
    name: "Project Auto Deploy"
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: rahasia
    url: jdbc:postgresql://156.67.219.132:5432/auto_deploy
    hikari:
      connection-timeout: 600000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 100
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080

data:
  DEPLOY_PATH: "src/main/resources/command"
